apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'io.spring.dependency-management'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:1.1.4'
    }
}

// Intentionally pinned to Java 8 so AWS Transform's managed Java
// language upgrade (Java 8/11 -> Java 17/21) is detected as an
// applicable transformation.
sourceCompatibility = 1.8
targetCompatibility = 1.8

mainClassName="com.amazonaws.samples.S3Sample"

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'software.amazon.awssdk:bom:2.29.0'
    }
}

dependencies {
    compile 'software.amazon.awssdk:s3'
    compile 'software.amazon.awssdk:dynamodb'
    compile 'software.amazon.awssdk:sqs'
    compile 'software.amazon.awssdk:sns'
    // Intentionally old dependencies to illustrate the tech debt that
    // AWS Transform's continuous modernization flow addresses.
    compile 'joda-time:joda-time:2.3'
    compile 'commons-lang:commons-lang:2.6'
}